app.action=encrypt
app.mode=daemon
app.in=/opt/data/inbox
app.out=/opt/data/outbox
app.scanIntervalMs=5000
app.recursive=true
app.includeHidden=false
app.shutdownWaitMs=3000
app.inProgressSuffix=.in_progress
