# Base runtime configuration
app.action=encrypt
app.mode=default
app.in=/opt/gpb/filecrypto/in
app.out=/opt/gpb/filecrypto/out
app.crl-file=/opt/gpb/filecrypto/crl/example.crl
app.scanIntervalMs=10000
app.recursive=false
app.includeHidden=false
app.shutdownWaitMs=3000
app.inProgressSuffix=.in_progress
